name: Playstations Repair
favicon: null
layout_spectrum: 0.74188
typography_spectrum: 0.57533
title: Playstation 4 - PS4 Repair
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-342620-19
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#052d73'
    - '#00abe1'
    - '#ffffff'
    - '#a6d7f5'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
