name: ps4repair
favicon: null
layout_spectrum: 0.09826582437381148
typography_spectrum: 0.5609055480454117
title: Playstationg 4 - PS4 Repair
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3133961108978838
  lightness: 0.6406724995467812
  saturation: 0.06447342806495726
  rhythmicContrast: 0.20941676758229733
purpose: []
